### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-tyrell#10]
# User Story
As a user, if I want to include an emoji I can type ":hamburger:" and a hamburger will show up in my comment

# AC
**WHEN** the user types in :hamburger:
**OR** something similar and presses enter 
**THEN** the comment will appear with the emoji in place of the word

# Development
* Create an emoji.json file in db that consists of an object filled with key/value pairs of 
```
":hamburger:" : "&#x1F354",
``` 
etc.
* Create an emojiData.js file that creates a `getEmoji` function that uses axios to get info
* Create a `replacer` function that takes in one variable (match) and runs the getEmoji function and places value onto a variable and then get the value of the variable[match] and return that.
* create a `newMessage` variable and run the code provided in comments that checks for ":something:"  and then replaces it with the proper unicode

**Comment by GregStephen** [comment]
regular expressions look it up!

**Comment by GregStephen** [comment]
possible regexp = :\S+:/gi 
```
const replacer = (match) => {
let emojiObj = emoji.getEmoji;
let unicode = emojiObj[match];
return unicode;
}
let message = input.value;
let newMessage = message.replace(regexp, replacer);
```
