### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-tyrell#18]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `db/messages.json`
**And** when they add messages it should add them to the list

## Dev Notes
* Create `util.js` and add a `printToDom` function
* Create `messageData.js` and create `getMessageData` function to use axios.get to retrieve from `db/messages.json` and export that function
* Create a `message.js` file and create a global variable `messages` that is an empty array. `messageDomStringBuilder` function that loops thru `messages` and builds a card with a name up top, time stamp next to that. Image below on left and message filling up the rest of the card.
* Create a `getMessages` function in `message.js` and call `getMessageData` and use .then and .catch. In .then assign data to `messages` variable and call `messageDomStringBuilder.
* Export `getMessages` and call on init in `main.js`

**Comment by GregStephen** [comment]
BootStrap media objects : https://getbootstrap.com/docs/4.3/components/media-object/
``` html
<div class="media">
  <img src="..." class="mr-3" alt="...">
  <div class="media-body">
    <h5 class="mt-0">Media heading</h5>
    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
  </div>
</div>
```
