### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-tyrell#2]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**GIVEN** A user navigates to your page
**THEN** they should see a navbar
**AND** it should have an application logo
**AND** it should have dropdown menu titled "Users" on the left with radio buttons to select a user
**AND** it should have a dropdown menu on the right titled "Options" with a "Clear" option
**AND** it should remain at the top of the screen if the page scrolls

## Dev Notes
* Create navbar on index.html
* Make it sticky icky
* Add logo to center of navbar
* Add bootstrap dropdown button on left with user options 
* Add bootstrap dropdown button on the right that has a "Clear" button
* Clear Button id = `clear-button`

**Comment by GregStephen** [comment]
bootstrap navbar : https://getbootstrap.com/docs/4.3/components/navbar/

^ Has references to adding dropdowns in the navbar

bootstrap dropdowns https://getbootstrap.com/docs/4.3/components/dropdowns/
