### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-house-tyrell#6]
1. Add a button/link to the UI labeled "Change Theme".
1. Remove the existing elements for changing the theme.
1. When user click on Change Theme element, show a Bootstrap modal dialog box.
1. Inside the modal, show two color picker fields - one for background color and one for font color.
1. Add a *Save* and *Cancel* button to modal.
1. When user clicks *Save* apply the chosen colors.

**Comment by GregStephen** [comment]
color picker: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by GregStephen** [comment]
<img width="452" alt="Screen Shot 2019-05-03 at 2 35 27 PM" src="https://user-images.githubusercontent.com/35859167/57161264-c1868100-6db0-11e9-8baa-83249e2f724d.png">
